- name: Deploy Flask App
  hosts: web
  become: true
  tasks:
    - name: Install Python3 and Git
      yum:
        name:
          - python3
          - git
        state: present

    - name: Install pip
      command: curl -O https://bootstrap.pypa.io/get-pip.py creates=/root/get-pip.py

    - name: Run get-pip.py
      command: python3 get-pip.py creates=/usr/local/bin/pip3

    - name: Install Flask using pip
      pip:
        name: Flask

    - name: Kill existing app.py process (if running)
      shell: |
        pgrep -f app.py && pkill -f app.py || echo "No app.py running"
      ignore_errors: yes

    - name: Clone Flask app repo
      git:
        repo: https://github.com/satya66655/flask-song-auto-update.git
        dest: /home/ec2-user/flask-song-auto-update
        force: yes
      become_user: ec2-user

    - name: Install dependencies from requirements.txt
      pip:
        requirements: /home/ec2-user/flask-song-auto-update/requirements.txt
      become_user: ec2-user

    - name: Run Flask app
      shell: nohup python3 app.py > app.log 2>&1 &
      args:
        chdir: /home/ec2-user/flask-song-auto-update
      become_user: ec2-user
    
    - name: Grant passwordless sudo to jenkins user
      lineinfile:
        path: /etc/sudoers.d/jenkins
        state: present
        create: yes
        mode: '0440'
        line: 'jenkins ALL=(ALL) NOPASSWD: ALL'

